### ISSUE TITLE
loading .bmp sidepics seems to crash springlobby

### ISSUE THREAD

**Issue by ashdnazg** [springlobby/springlobby#444]
happened in 0.219-gb56aecd by trying to change side in the singleplayer tab with S44:test

SIGTRAP backtrace:
```
#9  0x0072de69 in LSL::UnitsyncImage::MakeTransparent (this=0x28e850, r=3,
    g=17038254, b=30)
    at /home/vagrant/mxe/springlobby/src/lsl/src/lslunitsync/image.cpp:311
#10 0x007305f2 in LSL::UnitsyncImage::FromVfsFileData (data=0xe854428,
    size=<unknown type>, fn=0x28e81c, useWhiteAsTransparent=2685160)
    at /home/vagrant/mxe/springlobby/src/lsl/src/lslunitsync/image.cpp:163
```

segfault:

```
#0  UserList::GetNumUsers (this=0x0)
    at /home/vagrant/mxe/springlobby/src/userlist.cpp:86
#1  0x00510a7b in ChatPanel::UpdateUserCountLabel (this=0x0)
    at /home/vagrant/mxe/springlobby/src/gui/chatpanel.cpp:1187
#2  0x0051cee0 in ChatPanel::SetChannel (this=0x0,
    chan=0x53e9ac <MainChatTab::OnDisconnected()+2428>)
    at /home/vagrant/mxe/springlobby/src/gui/chatpanel.cpp:773
#3  0x0053e9ac in MainChatTab::OnDisconnected (this=0x0)
    at /home/vagrant/mxe/springlobby/src/gui/mainchattab.cpp:170
#4  0x005ab691 in Ui::OnDisconnected (this=0x0, server=0x0, wasonline=2685260)
    at /home/vagrant/mxe/springlobby/src/gui/ui.cpp:548
#5  0x004766c4 in ServerEvents::OnDisconnected (this=0x0, wasonline=0)
    at /home/vagrant/mxe/springlobby/src/serverevents.cpp:52
#6  0x004bcf36 in TASServer::OnDisconnected (this=0x0)
    at /home/vagrant/mxe/springlobby/src/tasserver.cpp:1753
#7  0x00480537 in Socket::OnSocketEvent (this=0x0, event=0x0)
    at /home/vagrant/mxe/springlobby/src/socket.cpp:147
#8  0x00d8f1e2 in wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandle
r::*)(wxEvent&), wxEvent&) const ()
#9  0x0e85c538 in ?? ()
```

**Comment by abma** [comment]
oh, indeed, i can reproduce this...

**Comment by abma** [comment]
more verbose stacktrace:

http://paste.springfiles.com/view/raw/341fa067

**Comment by abma** [comment]
jpn.png seems missing...

-> bmp loading is possible broken

**Comment by abma** [comment]
"Spring: 1944 dev-test-3738-b93ec89" doesn't make springlobby crash, so cause of the crash is the .bmp / the missing .png
