### ISSUE TITLE
Linux : Click on Chat Tab before logged / too early > Crash

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#662]
After launching SL, when I clic on [chat] (you only see the mouse position)... => https://youtu.be/qrk-SY21QCg
Look at the 2nd attempt !

No extra information, even if launched in command line.
You should click on the Chat tab quite early after SL launched, sometimes it doesn't crash (maybe if not early enough).

I know this is not really important to spend time on it... but this can maybe helpful to report.

**Comment by abma** [comment]
can't reproduce... 

can you run with gdb please and provide a backtrace?

**Comment by FabriceFABS** [comment]
Sorry abma I got no exp on GDB debbuging.
I got the package installed.
Can you guide me a bit to run SL in gdb ? Thank you...

**Comment by Usaga** [comment]
You need to do `gdb springlobby`, then when gdb starts type `run`. This will launch springlobby. Reproduce bug and switch back to gdb and type `bt` - this will printout stack trace. Post stact trace here, please. This will help us to investigate bug.

**Comment by FabriceFABS** [comment]
Yeah !! Thx ! And done it.

```
fabrice@FABS-PC:~$ gdb '/home/fab/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby' 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/fab/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby...done.
(gdb) run
Starting program: /home/fab/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe557d700 (LWP 3803)]
[New Thread 0x7fffd668a700 (LWP 3804)]
27x (springlobby:3799): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
[New Thread 0x7fffcbfff700 (LWP 3805)]
[Thread 0x7fffcbfff700 (LWP 3805) exited]
[Thread 0x7fffe557d700 (LWP 3803) exited]
[Thread 0x7ffff7fa4a40 (LWP 3799) exited]
[Inferior 1 (process 3799) exited normally]
(gdb) run
Starting program: /home/fab/Applications/Jeux/SpringRTS/SpringLobby/usr/local/bin/springlobby 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe557d700 (LWP 3809)]
[New Thread 0x7fffd668a700 (LWP 3810)]
27x (springlobby:3808): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
[New Thread 0x7fffcbfff700 (LWP 3811)]
[Thread 0x7fffcbfff700 (LWP 3811) exited]

Program received signal SIGSEGV, Segmentation fault.
0x000000000064badb in NickDataViewCtrl::SetUsers(std::map<std::string, User*, std::less<std::string>, std::allocator<std::pair<std::string const, User*> > > const&) ()
```

And your `bt` request :
```
(gdb) bt
#0  0x000000000064badb in NickDataViewCtrl::SetUsers(std::map<std::string, User*, std::less<std::string>, std::allocator<std::pair<std::string const, User*> > > const&) ()
#1  0x00000000005e610a in ChatPanel::OnLogin(wxCommandEvent&) ()
#2  0x00007ffff60ad11e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#3  0x00007ffff6220282 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#4  0x00007ffff62205e6 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#5  0x00007ffff622066e in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff6220703 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff6220765 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x00007ffff6221783 in wxEvtHandler::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff60b0cd7 in wxAppConsoleBase::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#10 0x00007ffff6726902 in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#11 0x00007ffff6726a13 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#12 0x00007ffff20d1ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff20d2048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff20d230a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff2e2e577 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#16 0x00007ffff6739145 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#17 0x00007ffff60ef440 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#18 0x00007ffff60af1fd in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#19 0x00007ffff613b04d in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#20 0x00000000004d0c28 in main ()
(gdb) 
```
