### ISSUE TITLE
SIGSEGV in NickDataViewModel::GetValue

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#780]
```
Program received signal SIGSEGV, Segmentation fault.
0x000002aaab0ae3ba in NickDataViewModel::GetValue(wxVariant&, wxDataViewItem const&, unsigned int) const ()
(gdb) bt
#0  0x000002aaab0ae3ba in NickDataViewModel::GetValue(wxVariant&, wxDataViewItem const&, unsigned int) const ()
#1  0x000003fff6e043e8 in wxGtkTreeCellDataFunc () from /usr/lib64/libwx_gtk2u_adv-3.0.so.0
#2  0x000003fff1966faa in gtk_tree_view_column_cell_set_cell_data () from /usr/lib64/libgtk-x11-2.0.so.0
#3  0x000003fff194f2c0 in gtk_tree_view_bin_expose () from /usr/lib64/libgtk-x11-2.0.so.0
#4  0x000003fff1950bf5 in gtk_tree_view_expose () from /usr/lib64/libgtk-x11-2.0.so.0
#5  0x000003fff1820384 in _gtk_marshal_BOOLEAN__BOXED () from /usr/lib64/libgtk-x11-2.0.so.0
#6  0x000003fff798094d in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#7  0x000003fff79982aa in signal_emit_unlocked_R () from /usr/lib64/libgobject-2.0.so.0
#8  0x000003fff79a0f52 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#9  0x000003fff79a162b in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#10 0x000003fff197a8fc in gtk_widget_event_internal () from /usr/lib64/libgtk-x11-2.0.so.0
#11 0x000003fff181e602 in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
#12 0x000003fff143cc1f in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#13 0x000003fff143cbc5 in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#14 0x000003fff143cbc5 in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#15 0x000003fff143cbc5 in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#16 0x000003fff143cbc5 in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#17 0x000003fff143cbc5 in _gdk_window_process_updates_recurse () from /usr/lib64/libgdk-x11-2.0.so.0
#18 0x000003fff1438a78 in gdk_window_process_updates_internal () from /usr/lib64/libgdk-x11-2.0.so.0
#19 0x000003fff143979d in gdk_window_process_updates () from /usr/lib64/libgdk-x11-2.0.so.0
#20 0x000003fff6372c59 in wxWindow::Update() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#21 0x000003fff63bac79 in wxStatusBar::DoUpdateStatusText(int) () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#22 0x000002aaab07acc9 in Statusbar::OnUpdateMsg(wxCommandEvent&) ()
#23 0x000003fff5c543f2 in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib64/libwx_baseu-3.0.so.0
#24 0x000003fff5df655f in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib64/libwx_baseu-3.0.so.0
#25 0x000003fff5df6673 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib64/libwx_baseu-3.0.so.0
#26 0x000003fff5df6ac0 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib64/libwx_baseu-3.0.so.0
#27 0x000003fff5df6b53 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib64/libwx_baseu-3.0.so.0
#28 0x000003fff5df6bc6 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib64/libwx_baseu-3.0.so.0
#29 0x000003fff5df7dc0 in wxEvtHandler::ProcessPendingEvents() () from /usr/lib64/libwx_baseu-3.0.so.0
#30 0x000003fff5c5841f in wxAppConsoleBase::ProcessPendingEvents() () from /usr/lib64/libwx_baseu-3.0.so.0
#31 0x000003fff6320e92 in wxApp::DoIdle() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#32 0x000003fff6320fd6 in wxapp_idle_callback () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#33 0x000003fff347c36d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#34 0x000003fff347c748 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0
#35 0x000003fff347cbe2 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#36 0x000003fff181cb77 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#37 0x000003fff6343695 in wxGUIEventLoop::DoRun() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#38 0x000003fff5c9c240 in wxEventLoopBase::Run() () from /usr/lib64/libwx_baseu-3.0.so.0
#39 0x000003fff5c567ac in wxAppConsoleBase::MainLoop() () from /usr/lib64/libwx_baseu-3.0.so.0
#40 0x000003fff5cf36f8 in wxEntry(int&, wchar_t**) () from /usr/lib64/libwx_baseu-3.0.so.0
#41 0x000002aaaaed20cd in main ()
```

**Comment by specing** [comment]
See also #662
