### ISSUE TITLE
Channel::IsSubscribed() segfaults

### ISSUE THREAD

**Issue by specing** [springlobby/springlobby#796]
From a week ago, on what was probably latest git:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000005d80eaa9c9 in Channel::IsSubscribed() ()
```
Backtrace:
```
#0  0x0000005d80eaa9c9 in Channel::IsSubscribed() ()
#1  0x0000005d80f7353c in ChatPanelMenu::GetMenu() ()
#2  0x0000005d80fd58d2 in SLChatNotebook::OnHeaderRightClick(wxAuiNotebookEvent&) ()
#3  0x0000036e8973f87d in ?? ()```

**Comment by specing** [comment]
Today:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000016ccd759c9 in Channel::IsSubscribed() ()
(gdb) bt
#0  0x00000016ccd759c9 in Channel::IsSubscribed() ()
#1  0x00000016cce3e53c in ChatPanelMenu::GetMenu() ()
#2  0x00000016cce507ad in ChatPanel::OnMouseDown(wxMouseEvent&) ()
```
