### ISSUE TITLE
I can't download BA test version

### ISSUE THREAD

**Issue by triton13** [springlobby/springlobby#823]
I used to delete rapid folder and package folder to be able to work around this issue, looks like it doesnt work today.

**Comment by abma** [comment]
springlobby.log when download fails, please.

**Comment by triton13** [comment]
will do next time

2018-02-13 23:05 GMT+01:00 abma <notifications@github.com>:

**Comment by specing** [comment]
Abma I'm pretty sure Github issues support making an "issue template" where log could be explicitly requested from reporters.

**Comment by silentwings** [comment]
Trying to dl a second time immediately after the failed dl (without deleting pool and so on) has just worked.

**Comment by abma** [comment]
seems its time for writing automatic tests for rapid downloads

**Comment by silentwings** [comment]
Fyi, based on watching the channels, I think the number of downloads that fail in SL has increased rapidly in recent weeks.

**Comment by abma** [comment]
i'm on this bug: gimme some time

**Comment by abma** [comment]
seems like it fails server side, even the old "rapid" fails with:

rapid pin techa:test
Using data directory: /home/abma/.spring
Pinning: techa:test
Installing: Tech Annihilation test-8230-51d41e4
Traceback (most recent call last):===88%============================>         ]
  File "bin/rapid", line 7, in <module>
    main()
  File "/home/abma/Projects/rapid/rapid/ui/text/main.py", line 131, in main
    pin(req_arg())
  File "/home/abma/Projects/rapid/rapid/main.py", line 42, in pin
    install_single(rapid.packages[t])
  File "/home/abma/Projects/rapid/rapid/main.py", line 68, in install_single
    p.install(ProgressBar())
  File "/home/abma/Projects/rapid/rapid/rapid.py", line 543, in install
    self.download_files(self.missing_files, progress)
  File "/home/abma/Projects/rapid/rapid/rapid.py", line 515, in download_files
    if md5(g.read()).digest() != f.md5:
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

**Comment by abma** [comment]
side note: downloading again works. seems only large downloads are affected.

**Comment by abma** [comment]
side note: when searching for bugs i heavily refactored pr-downloader which maybe fixed some other bugs, too.

-> when it still fails, please report back
