### ISSUE TITLE
crash by unitsync 104.0.1-774-gbe77231 develop

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#855]
```
Thread 1 "springlobby" received signal SIGSEGV, Segmentation fault.
0x00007fffd9e1598e in boost::detail::sp_counted_impl_p<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >::dispose() ()
   from /home/abma/.spring/engine/104.0.1-774-gbe77231 develop/libunitsync.so
(gdb) bt
#0  0x00007fffd9e1598e in boost::detail::sp_counted_impl_p<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >::dispose() ()
    at /home/abma/.spring/engine/104.0.1-774-gbe77231 develop/libunitsync.so
#1  0x00007fffd9e15c5a in boost::detail::sp_counted_impl_p<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > >::dispose() () at /home/abma/.spring/engine/104.0.1-774-gbe77231 develop/libunitsync.so
#2  0x00007fffd9d8a02d in boost::detail::sp_counted_base::release() (this=0x6030047cf950) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#3  0x00007fffd9d8a02d in boost::detail::shared_count::~shared_count (this=0x7fffffff6cf8, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#4  0x00007fffd9d8a02d in boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > >::~shared_ptr (this=0x7fffffff6cf0, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#5  0x00007fffd9d8a02d in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::~basic_regex (this=0x7fffffff6cf0, __in_chrg=<optimized out>) at /usr/include/boost/regex/v4/basic_regex.hpp:346
#6  0x00007fffd9d8a02d in FileSystem::GetNormalizedPath(std::string const&) (path="/mnt/tmp/home/.spring/engine/104.0.1-774-gbe77231 develop//isolated.txt")
    at ../../rts/System/FileSystem/FileSystem.cpp:223
#7  0x00007fffd9d8a625 in FileSystem::FileExists(std::string) (file="/mnt/tmp/home/.spring/engine/104.0.1-774-gbe77231 develop//isolated.txt")
    at ../../rts/System/FileSystem/FileSystem.cpp:116
#8  0x00007fffd9d76f59 in DataDirLocater::UpdateIsolationModeByEnvVar() (this=this@entry=0x606000364580) at ../../rts/System/FileSystem/DataDirLocater.cpp:97
#9  0x00007fffd9d77f36 in DataDirLocater::DataDirLocater() (this=0x606000364580) at ../../rts/System/FileSystem/DataDirLocater.cpp:80
#10 0x00007fffd9d77fab in DataDirLocater::GetInstance() () at ../../rts/System/FileSystem/DataDirLocater.cpp:578
#11 0x00007fffd9e082e9 in Init(bool, int) (isServer=<optimized out>, id=<optimized out>) at ../../tools/unitsync/unitsync.cpp:384
#12 0x0000555556ab556d in LSL::UnitsyncLib::_Init() (this=0x61a000049e80) at src/downloader/lib/src/lsl/lslunitsync/c_api.cpp:142
#13 0x0000555556ab50a2 in LSL::UnitsyncLib::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61a000049e80, path="/home/abma/.spring/engine/104.0.1-774-gbe77231 develop/libunitsync.so") at src/downloader/lib/src/lsl/lslunitsync/c_api.cpp:107
#14 0x0000555556a0cac2 in LSL::Unitsync::LoadUnitSyncLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x616000033980, unitsyncloc="/home/abma/.spring/engine/104.0.1-774-gbe77231 develop/libunitsync.so") at src/downloader/lib/src/lsl/lslunitsync/unitsync.cpp:96
#15 0x0000555556a1753e in LSL::Unitsync::ReloadUnitSyncLib() (this=0x616000033980) at src/downloader/lib/src/lsl/lslunitsync/unitsync.cpp:691
#16 0x0000555556641663 in Ui::NeedsDownload(IBattle const*, bool, DownloadEnum::Category) (this=0x60f000027730, battle=
    0x61d0002ea480, uiprompt=true, cat=DownloadEnum::CAT_NONE) at src/gui/ui.cpp:941
#17 0x0000555556718746 in BattleRoomTab::SetBattle(IBattle*) (this=0x61a00003a880, battle=0x61d0002ea480) at src/gui/hosting/battleroomtab.cpp:1307
#18 0x0000555556731c54 in MainJoinBattleTab::JoinBattle(IBattle&) (this=0x617000078900, battle=...) at src/gui/hosting/mainjoinbattletab.cpp:105
#19 0x0000555556636cd6 in Ui::OnJoinedBattle(IBattle&) (this=0x60f000027730, battle=...) at src/gui/ui.cpp:588
#20 0x00005555563fa6c0 in ServerEvents::OnJoinedBattle(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x608000100920, battleid=409701, hash="3720702404") at src/serverevents.cpp:282
#21 0x00005555564607b3 in TASServer::ExecuteCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (this=0x6190002c0180, cmd="JOINBATTLE", inparams="409701 -574264892", replyid=13) at src/tasserver.cpp:752
#22 0x0000555556459302 in TASServer::ExecuteCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x6190002c0180, in="#13 JOINBATTLE 409701 -574264892") at src/tasserver.cpp:503
#23 0x000055555648de4a in TASServer::OnDataReceived() (this=0x6190002c0180) at src/tasserver.cpp:1857
#24 0x000055555641a7aa in Socket::OnSocketEvent(wxSocketEvent&) (this=0x6160000e4c80, event=...) at src/socket.cpp:62
#25 0x00007ffff3e998ce in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
---Type <return> to continue, or q <return> to quit---
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#26 0x00007ffff3e999d3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#27 0x00007ffff3e99d9b in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#28 0x00007ffff3e99e23 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#29 0x00007ffff3e99e85 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#30 0x00007ffff3e9aff2 in wxEvtHandler::ProcessPendingEvents() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#31 0x00007ffff3d1bdf7 in wxAppConsoleBase::ProcessPendingEvents() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#32 0x00007ffff439c78d in wxApp::DoIdle() (this=0x617000000400) at ../src/gtk/app.cpp:157
#33 0x00007ffff439c893 in wxapp_idle_callback(gpointer) () at ../src/gtk/app.cpp:107
#34 0x00007fffee2b00f5 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007fffee2b04c0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fffee2b07d2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fffef01b977 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#38 0x00007ffff43bc6d5 in wxGUIEventLoop::DoRun() (this=0x6060002ca320) at ../src/gtk/evtloop.cpp:65
#39 0x00007ffff3d55ea3 in wxEventLoopBase::Run() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#40 0x00007ffff3d1d4b6 in wxAppConsoleBase::MainLoop() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#41 0x00007ffff3da7ef9 in wxEntry(int&, wchar_t**) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#42 0x000055555643cdc8 in main(int, char**) (argc=2, argv=0x7fffffffe918) at src/springlobbyapp.cpp:70

```

**Comment by abma** [comment]
atm looks like a new bug in unitsync

**Comment by abma** [comment]
104.0.1-409-g07c2800 maintenance crashes for me, too

**Comment by abma** [comment]
possible caused by https://svn.boost.org/trac10/ticket/5911

**Comment by abma** [comment]
boost is gone in spring, so this crash should be gone, too
